USE [Garage]
GO

/****** Object:  Table [dbo].[Autos]    Script Date: 24/04/2022 11:24:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Autos](
	[Nummerplaat] [nvarchar](255) NOT NULL,
	[Model] [nvarchar](255) NOT NULL,
	[Merk] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Nummerplaat] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


